import HuaweiImg from '../../../assets/images/HUAWEI_Image.png'
import HonorImg from '../../../assets/images/HONOR_Image.png'
import XiaomiImg from '../../../assets/images/XIAOMI_Image.png'

export const categoryProduct = {
   category: [
      { id: '1', name: 'Смартфоны' },
      { id: '2', name: 'Смарт-часы и браслеты' },
      { id: '3', name: 'Ноутбуки' },
      { id: '4', name: 'Планшеты' },
   ],
   subcategory: [
      { id: '1', name: 'Ремешки для часов' },
      { id: '2', name: 'Зарядные устройства' },
      { id: '3', name: 'Защита экрана' },
      { id: '4', name: 'Чехлы и корпусы' },
      { id: '5', name: 'Подставки' },
      { id: '6', name: 'Кабели и адаптеры' },
      { id: '7', name: 'Внешние аккумуляторы' },
      { id: '8', name: 'Техника' },
      { id: '9', name: 'Technique' },
   ],
   brand: [
      {
         id: '1',
         image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/2560px-Samsung_Logo.svg.png',
         name: 'Samsung',
      },
      {
         id: '2',
         image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/625px-Apple_logo_black.svg.png',
         name: 'Apple',
      },
      { id: '3', image: HuaweiImg, name: 'Huawei' },
      { id: '4', image: HonorImg, name: 'Honor' },
      { id: '5', image: XiaomiImg, name: 'Xiaomi' },
   ],
   subcategorySmartphones: [
      { id: '1', name: 'Samsung' },
      { id: '2', name: 'Apple' },
      { id: '3', name: 'Huawei' },
      { id: '4', name: 'Honor' },
      { id: '5', name: 'Xiaomi' },
   ],
   subcategorySmartWatch: [
      { id: '1', name: 'Смарт-часы Apple Watch' },
      { id: '2', name: 'Умные часы для взрослых' },
      { id: '3', name: 'Умные часы для детей' },
      { id: '4', name: 'Фитнес браслеты' },
      { id: '5', name: 'Xiaomi' },
   ],
   subcategoryNotebooks: [
      { id: '1', name: 'Acer' },
      { id: '2', name: 'Asus' },
      { id: '3', name: 'Apple' },
      { id: '4', name: 'DELL' },
      { id: '5', name: 'Digma' },
      { id: '6', name: 'Huawei' },
      { id: '7', name: 'HONOR' },
      { id: '8', name: 'Lenovo' },
      { id: '9', name: 'HP' },
      { id: '10', name: 'MSI' },
      { id: '11', name: 'Xiaomi' },
   ],
   subcategoryTablets: [
      { id: '1', name: 'Acer' },
      { id: '2', name: 'Asus' },
      { id: '3', name: 'Apple' },
      { id: '4', name: 'DELL' },
      { id: '5', name: 'Digma' },
      { id: '6', name: 'Huawei' },
      { id: '7', name: 'HONOR' },
      { id: '8', name: 'Lenovo' },
      { id: '9', name: 'HP' },
      { id: '10', name: 'MSI' },
      { id: '11', name: 'Xiaomi' },
   ],
}

export const dataProductWatch = {
   rom: [
      { id: '1', name: '4' },
      { id: '2', name: '8' },
      { id: '3', name: '16' },
      { id: '4', name: '32' },
   ],
   bracelet: [
      { id: '1', name: 'Силикон' },
      { id: '2', name: 'Кожа' },
      { id: '3', name: 'Резина' },
      { id: '4', name: 'Пластик' },
      { id: '5', name: 'Нейлон' },
      { id: '6', name: 'Из искусственной кожи ' },
      { id: '7', name: 'Имитация керамики' },
   ],
   housingMaterial: [
      { id: '1', name: 'Акриловый' },
      { id: '2', name: 'Алюминий' },
      { id: '3', name: 'Керамика' },
      { id: '4', name: 'Пластик' },
      { id: '5', name: 'Металл' },
      { id: '6', name: 'Нержавейщая сталь' },
      { id: '7', name: 'Стекло' },
   ],
   display: [
      { id: '1', name: '1.2' },
      { id: '2', name: '1.22' },
      { id: '3', name: '1.3' },
      { id: '4', name: '1.4' },
      { id: '5', name: '1.41' },
      { id: '6', name: '1.44' },
      { id: '7', name: '1.54' },
   ],
}

export const dataProductSmartphones = {
   romSmartphones: [
      { id: '1', name: '8' },
      { id: '2', name: '16' },
      { id: '3', name: '32' },
      { id: '4', name: '64' },
      { id: '5', name: '128' },
      { id: '6', name: '256' },
      { id: '7', name: '512' },
   ],
   smartphonesRAM: [
      { id: '1', name: '2' },
      { id: '2', name: '4' },
      { id: '3', name: '6' },
      { id: '4', name: '8' },
      { id: '5', name: '12' },
   ],
   smartphonesSIMcards: [
      { id: '1', name: '1' },
      { id: '2', name: '2' },
   ],
}

export const dataProductNotebooks = {
   processorNotebooks: [
      { id: '1', name: 'Intel Core i3' },
      { id: '2', name: 'Intel Core i5' },
      { id: '3', name: 'Intel Core i7' },
      { id: '4', name: 'Intel Core i9' },
      { id: '5', name: 'Intel Celeron' },
      { id: '6', name: 'Intel Pentium' },
      { id: '7', name: 'AMD' },
      { id: '8', name: 'Intel Quad Core' },
      { id: '9', name: 'Intel Dual Core' },
      { id: '10', name: 'AMD Ryzen 3 3250U' },
      { id: '11', name: 'Intel Core i7-8565U' },
      { id: '12', name: 'AMD Ryzen 7 4700U' },
   ],
   screenResolutionNotebooks: [
      { id: '1', name: '1024x600' },
      { id: '2', name: '1280x800' },
      { id: '3', name: '1366x768' },
      { id: '4', name: '1600x900' },
      { id: '5', name: '1920x1080' },
      { id: '6', name: '2160x1440' },
      { id: '7', name: '2560x1600' },
      { id: '8', name: '3072x1920' },
      { id: '9', name: '3840x2160' },
   ],
   purposeNotebooks: [
      { id: '1', name: 'Для работы' },
      { id: '2', name: 'Мультимедийный' },
      { id: '3', name: 'Игровой' },
      { id: '4', name: 'Для бизнеса' },
      { id: '5', name: 'Для учебы' },
      { id: '6', name: 'Офисный' },
   ],
   videoMemoryNotebooks: [
      { id: '1', name: '2' },
      { id: '2', name: '4' },
      { id: '3', name: '6' },
      { id: '4', name: '8' },
      { id: '5', name: '16' },
   ],
   ramNotebooks: [
      { id: '1', name: '2' },
      { id: '2', name: '4' },
      { id: '3', name: '8' },
      { id: '4', name: '16' },
      { id: '5', name: '32' },
      { id: '6', name: '64' },
   ],
   screenSizeNotebooks: [
      { id: '1', name: '11.6' },
      { id: '2', name: '13.3' },
      { id: '3', name: '14' },
      { id: '4', name: '15' },
      { id: '5', name: '15.6' },
      { id: '6', name: '16' },
      { id: '7', name: '16.1' },
      { id: '8', name: '17.8' },
   ],
}

export const dataProductTablets = {
   screenResolutionTablets: [
      { id: '1', name: '1600x900' },
      { id: '2', name: '1366x768' },
      { id: '3', name: '1920x1080' },
      { id: '4', name: '2560x1600' },
      { id: '5', name: '3072x1920' },
      { id: '6', name: '3840x2160' },
   ],
   screenSizeTablets: [
      { id: '1', name: '14' },
      { id: '2', name: '15' },
      { id: '3', name: '16' },
      { id: '4', name: '11.6' },
      { id: '5', name: '13.3' },
      { id: '6', name: '15.6' },
      { id: '7', name: '16.1' },
      { id: '8', name: '17.3' },
   ],
   romTablets: [
      { id: '1', name: '8' },
      { id: '2', name: '16' },
      { id: '3', name: '32' },
      { id: '4', name: '64' },
      { id: '5', name: '128' },
      { id: '6', name: '256' },
   ],
   ramTablets: [
      { id: '1', name: '2' },
      { id: '2', name: '4' },
      { id: '3', name: '6' },
      { id: '4', name: '8' },
      { id: '5', name: '12' },
   ],
   screenDiagonalTablets: [
      { id: '1', name: '0 - 2' },
      { id: '2', name: '3 - 5' },
      { id: '3', name: '6 - 8' },
      { id: '4', name: '9 - 11' },
      { id: '5', name: '12 - 15' },
   ],
   batteryCapacity: [
      { id: '1', name: '0 - 2399 мА/час' },
      { id: '2', name: '2400 - 4799 мА/час' },
      { id: '3', name: '4800 - 7199 мА/час' },
      { id: '4', name: '7200 - 9599 мА/ч' },
      { id: '5', name: '9600 - 12000 мА/ч' },
   ],
}

export const radioData = {
   genderRadioData: [
      { id: '1', label: 'Унисекс', value: 'UNISEX' },
      { id: '2', label: 'Женский', value: 'FEMALE' },
      { id: '3', label: 'Мужской', value: 'MALE' },
   ],
   waterproof: [
      { id: '1', label: 'Да', value: true },
      { id: '2', label: 'Нет', value: false },
   ],
   anInterface: [
      { id: '1', label: 'Bluetooth', value: 'BLUETOOTH' },
      { id: '2', label: 'Wi-Fi', value: 'WI-FI' },
      { id: '3', label: 'GPS', value: 'GPS' },
      { id: '4', label: 'NFC', value: 'NFC' },
   ],
   hullShape: [
      { id: '1', label: 'Квадратная', value: 'SQUARE' },
      { id: '2', label: 'Круглая', value: 'ROUND' },
      { id: '3', label: 'Овальная', value: 'OVAL' },
      { id: '4', label: 'Прямоугольная', value: 'RECTANGULAR' },
   ],
}

//! #E1E1E1
//! #732600

export const bgColor = [
   '#FFFFFF',
   '#CCCCCC',
   '#B2B2B2',
   '#9C9C9C',
   '#686868',
   '#343434',
   '#000000',
   '#FFBEBE',
   '#CD6666',
   '#FF0000',
   '#E60000',
   '#A80000',
   '#730000',
   '#F57A7A',
   '#894444',
   '#FFEBBE',
   '#FFA77F',
   '#FF5500',
   '#D7B09E',
   '#CD8966',
   '#895A44',
   '#FFD37F',
   '#FFAA00',
   '#E69800',
   '#A87000',
   '#734C00',
   '#D7C29E',
   '#F5CA7A',
   '#CDAA66',
   '#FFFFBE',
   '#FFFF72',
   '#E6E600',
   '#A8A800',
   '#737300',
   '#CDCD66',
   '#898944',
   '#D1FF73',
   '#AAFF00',
   '#4CE600',
   '#38A800',
   '#267300',
   '#A5F57A',
   '#5C8944',
   '#BEFFE8',
   '#72FFE0',
   '#00FFC5',
   '#00E6A9',
   '#00A884',
   '#00734C',
   '#9ED7C2',
   '#66CDAB',
   '#BEE8FF',
   '#73DFFF',
   '#00C5FF',
   '#00A9E6',
   '#0084A8',
   '#004C73',
   '#9EBBD7',
   '#6699CD',
   '#BED2FF',
   '#73B2FF',
   '#0071FF',
   '#005CE6',
   '#004DA8',
   '#002673',
   '#9EAAD7',
   '#7A8EF5',
   '#172973',
   '#012E95',
   '#040097',
   '#00329A',
   '#0A29C0',
   '#3B3AC4',
   '#035FE4',
   '#0370CB',
   '#E8BEFF',
   '#C500FF',
   '#A900E6',
   '#8400A8',
   '#4C0073',
   '#C29ED7',
   '#AA66CD',
   '#704489',
   '#FFBEE8',
   '#FF73DF',
   '#FF00C5',
   '#A80084',
   '#73004C',
   '#D69DBC',
   '#CD6699',
   '#894465',
]
